# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ca272be2d8e0d182c5fe715277775247916321cc95b68ac946724b95875b840d0edae14239c1f4a804995229d49c103c1e04bc24d004dbf0a82dc0fa7f1b95f

test:
  secret_key_base: fd7261e4d29d34f641162c1624c3993fd1b2b2aea890f96507797b2eaaa514716057e9263c97d1245349ec996521e01129a61e178861144e2fed072a3ac1d4c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
